### ISSUE TITLE
help

### ISSUE THREAD

**Issue by harli65** [wahasa/Ubuntu#23]
root@localhost:~# vnc-start

New Xtigervnc server 'remote-desktop' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /tmp/tigervnc.Fr0kre/passwd :1 to connect to the VNC server.

=================== tail /root/.vnc/localhost:1.log ===================
[mi] mieq: warning: overriding existing handler (nil) with 0x30001e1000 for event 2
[mi] mieq: warning: overriding existing handler (nil) with 0x30001e1000 for event 3
xrdb: No such file or directory
xrdb: can't open file '/root/.Xresources'
/root/.vnc/xstartup: line 4: startplasma-x11: command not found
=======================================================================

Session startup via '/root/.vnc/xstartup' exited with status 127!

Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
The X session exited with status 127!
Killing Xtigervnc process ID 7107... success!

**Comment by EmperorYeqing** [comment]
Pls a! Y solution for this

**Comment by EmperorYeqing** [comment]
Any solution for this yet
